<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>XlsxEditorPoc</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.2.0" />
  </ItemGroup>

</Project>
