<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NumDesTools.XlsxEditor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DataGridExtensions" Version="2.9.1" />
    <PackageReference Include="EPPlus" Version="8.2.0" />
    <PackageReference Include="Sylvan.Data.Excel" Version="0.5.7" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

</Project>
